Repository DEFRA/sroc-charging-module-api-docs, pull requests merged in 2021-12, with the labels that each got.

#1 Replace template content with draft spec
  .gitignore
  LICENSE
  README.md
  index.html
  openapi.yml
  swagger.yaml
Labels: enhancement

#2 Rename root openapi.yml to draft.yml
  draft.yml
  index.html
Labels: housekeeping

#3 Add the openapi spec files
  spec/openapi.yml
  spec/paths/admin/authorised_system.yml
  spec/paths/admin/authorised_systems.yml
  spec/paths/admin/bill_runs.yml
  spec/paths/admin/customers.yml
  spec/paths/admin/health/airbrake.yml
  spec/paths/admin/health/database.yml
  spec/paths/admin/regime.yml
  spec/paths/admin/regimes.yml
  spec/paths/admin/test/bill_runs.yml
  spec/paths/admin/test/customer.yml
  spec/paths/admin/test/customers.yml
  spec/paths/admin/test/data_export.yml
  spec/paths/admin/test/transaction.yml
  spec/paths/status.yml
  spec/paths/v2/bill_runs/bill_run.yml
  spec/paths/v2/bill_runs/bill_run_approve.yml
  spec/paths/v2/bill_runs/bill_run_generate.yml
  spec/paths/v2/bill_runs/bill_run_send.yml
  spec/paths/v2/bill_runs/bill_run_status.yml
  spec/paths/v2/bill_runs/bill_runs.yml
  spec/paths/v2/bill_runs/invoices/invoice.yml
  spec/paths/v2/bill_runs/invoices/invoice_rebill.yml
  spec/paths/v2/bill_runs/licences/licence.yml
  spec/paths/v2/bill_runs/transactions/bill_run_transactions.yml
  spec/paths/v2/calculate_charge/calculate_charge.yml
  spec/paths/v2/customer_changes/customer_changes.yml
  spec/paths/v2/customer_files/customer_files.yml
  spec/paths/v3/bill_runs/bill_runs.yml
  spec/paths/v3/bill_runs/transactions/bill_run_transactions.yml
  spec/paths/v3/calculate_charge/calculate_charge.yml
  spec/schema/fields.yml
  spec/schema/parameters.yml
  spec/schema/schemas.yml
Labels: enhancement

#4 Add previous versions
  versions/v0-10-1.yml
  versions/v0-12-0.yml
  versions/v0-13-0.yml
  versions/v0-13-1.yml
  versions/v0-13-2.yml
  versions/v0-13-3.yml
  versions/v0-14-0.yml
  versions/v0-14-1.yml
  versions/v0-14-2.yml
  versions/v0-15-0.yml
  versions/v0-2-0.yml
  versions/v0-3-0.yml
  versions/v0-4-0.yml
Labels: enhancement

#5 Add spec generator to the project
  .gitignore
  draft.yml
  package-lock.json
  package.json
Labels: enhancement

#6 Update README to match new repo and process
  README.md
  screenshots/api_screenshot.png
  screenshots/openapi_viewer.png
  screenshots/swagger_viewer.png
Labels: enhancement

#7 Fix update swagger-ui workflow
  .github/workflows/update-swagger.yml
Labels: bug

#9 CMEA-232 Add v3 delete invoice endpoint
  draft.yml
  spec/openapi.yml
  spec/paths/v2/bill_runs/invoices/invoice.yml
  spec/paths/v3/bill_runs/invoices/invoice.yml
Labels: enhancement

#8 Remove npx call in package.json start script
  package.json
Labels: housekeeping

#10 Update documentation around bill run statuses
  draft.yml
  spec/paths/v2/bill_runs/bill_run.yml
  spec/paths/v2/bill_runs/bill_run_generate.yml
  spec/paths/v2/bill_runs/bill_run_send.yml
  spec/paths/v2/bill_runs/bill_run_status.yml
  spec/schema/fields.yml
Labels: documentation

#11 Fix notes on viewing versions in the README
  README.md
  screenshots/openapi_viewer.png
  screenshots/select_version.png
Labels: bug
